package by.stepanovich.zkh.command;

public enum CommandName {

    CHANGE_LOCALE,
    LOG_IN,
    LOG_OUT,
    REGISTER,
    DEFAULT,
    SHOW_REGISTER,
    SHOW_LOGIN,
    USER_INFO,
    REGISTER_ORDER,
    SHOW_MAIN_PAGE,
    SHOW_REGISTER_REQUEST_PAGE,
    SHOW_ALL_USER_ORDERS,
    CANCEL_SINGLE_ORDER,
    SHOW_ALL_USERS,
    SHOW_ALL_ORDERS,
    MANAGER_TASK,
    UPDATE_PASSWORD,
    PASSWORD_CHANGE_PAGE,
    UPDATE_PROFILE_PAGE,
    ASSIGN_PERFORMER_PAGE,
    ASSIGN_PERFORMER,
    FIND_PERFORMER,
    UPDATE_PROFILE;
}
