package by.stepanovich.zkh.command;

public class PathOfJsp {
    public static final String SHOW_MAIN_PAGE = "/WEB-INF/jsp/common/homePage.jsp";
    public static final String SHOW_MAIN_PAGE_CONTROLLER = "controller?command=show_main_page";
    public static final String SHOW_USER_LOGIN_PAGE = "/WEB-INF/jsp/common/loginPage.jsp";
    public static final String SHOW_REGISTER_PAGE = "/WEB-INF/jsp/common/register.jsp";
    public static final String SHOW_REGISTER_SUCCESS = "controller?command=register_success_page";
    public static final String REGISTER_SUCCESS_PAGE = "/WEB-INF/jsp/common/registerSuccess.jsp";
    public static final String SHOW_PROFILE_PAGE = "/WEB-INF/jsp/common/userInfo.jsp";
    public static final String SHOW_PROFILE_PAGE_COMMAND = "controller?command=user_info";
    public static final String USER_REGISTER_ORDER = "/WEB-INF/jsp/user/registerOrder.jsp";
    public static final String SHOW_REQUEST_ACCEPTED_COMMAND = "controller?command=register_order_success";
    public static final String SHOW_REQUEST_ACCEPTED = "/WEB-INF/jsp/user/requestAccepted.jsp";
    public static final String ALL_USER_ORDERS_COMMAND = "controller?command=show_all_user_orders";
    public static final String ERROR_500_PAGE = "/WEB-INF/jsp/error/error500.jsp";
    public static final String ERROR_404_PAGE = "/WEB-INF/jsp/error/error404.jsp";
    public static final String ALL_USER_ORDERS_VIEW = "/WEB-INF/jsp/user/allUserOrdersView.jsp";
    public static final String BUILD_ORDER_REPORT = "/WEB-INF/jsp/reports/ordersReport.jsp";
    public static final String BUILD_USER_REPORT = "/WEB-INF/jsp/reports/usersReport.jsp";
    public static final String MANAGER_PAGE = "/WEB-INF/jsp/manager/managerTask.jsp";
    public static final String COMMAND_PASSWORD_CHANGED = "controller?command=password_changed";
    public static final String PASSWORD_CHANGED = "/WEB-INF/jsp/common/passwordChanged.jsp";
    public static final String PASSWORD_CHANGE_PAGE = "/WEB-INF/jsp/common/passwordUpdate.jsp";
    public static final String UPDATE_PROFILE_PAGE = "/WEB-INF/jsp/common/updateProfile.jsp";
    public static final String ASSIGN_PERFORMER_PAGE = "/WEB-INF/jsp/manager/showNewOrders.jsp";
    public static final String ASSIGN_PERFORMER = "/WEB-INF/jsp/manager/assignPerformer.jsp";
    public static final String CHOOSE_PERFORMER = "/WEB-INF/jsp/manager/choosePerformer.jsp";
    public static final String ASSIGN_PERFORMER_PAGE_CONTROLLER = "controller?command=assign_performer_page";
    public static final String EMPLOYEE_TASK = "/WEB-INF/jsp/employee/employeeTask.jsp";
    public static final String FIND_PERFORMER_COMMAND = "controller?command=find_performer";
    public static final String SHOW_ADD_ADMIN_COMMAND = "controller?command=show_add_admin_page";
    public static final String ADD_ADMIN = "/WEB-INF/jsp/manager/changeRole.jsp";
    public static final String SHOW_REGISTER_EMPLOYEE_PAGE = "/WEB-INF/jsp/employee/registerEmployee.jsp";
    public static final String SHOW_REGISTER_EMPLOYEE_PAGE_COMMAND = "controller?command=register_employee_page";
    public static final String ACCEPT_EMPLOYEE_PAGE_CONTROLLER = "controller?command=accept_employee_page";
    public static final String ACCEPT_EMPLOYEE_PAGE = "/WEB-INF/jsp/manager/acceptEmployeeRegister.jsp";
    public static final String CHECK_CLOSED_BY_EMPLOYEE_PAGE = "/WEB-INF/jsp/manager/closedByEmployeeOrders.jsp";
    public static final String CHECK_CLOSED_BY_EMPLOYEE_PAGE_COMMAND = "controller?command=check_closed_applications";
    public static final String SHOW_ORDERS_AT_WORK = "/WEB-INF/jsp/manager/showOrdersAtWork.jsp";
    public static final String REGISTER_AS_EMPLOYEE_SUCCESS_COMMAND = "controller?command=register_as_employee_success";
    public static final String REGISTER_AS_EMPLOYEE_SUCCESS= "/WEB-INF/jsp/user/registerAsEmployeeSuccess.jsp";
}
